<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Javascript Promise Cheatsheet</title>
    <meta name="description" content="Javascript Promise Cheatsheet">
    <meta name="author" content="Maurycy Zarzycki, Retrocade.net">


    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"
            integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
    <script src="js/prism.js"></script>
    <script src="js/scripts.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Inconsolata|Open+Sans:400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="css/prism.css">
    <link rel="stylesheet" href="css/style.css">
</head>

<body>
<article>
    <header>
        <h1>JS Promise cheatsheet</h1>
        <section>
            <p>
                This document contains various examples on how promises behave in different situations. It is created
                and maintained by <a href="https://github.com/RetrocadeNet/">Maurycy Zarzycki, Retrocade.net</a>, its
                source is available on <a href="https://github.com/RetrocadeNet/Promise-cheatsheet">Github</a>. All
                suggestions and issues can be communicated via Github's
                <a href="https://github.com/RetrocadeNet/Promise-cheatsheet/issues">Issues page</a>.
            </p>
            <p>
                Recommended reading: <a href="https://promisesaplus.com/">Promises/A+</a>.
            </p>
        </section>
    </header>
    <section class="toc">
        <header>
            <h2>Table of Contents</h2>
        </header>
        <article>
            <section>
                <ul>
                    <li><a href="#promise-vocabulary">Promise vocabulary</a></li>
                </ul>
            </section>
        </article>
    </section>
    <section class="promise-vocabulary">
        <header>
            <h2 id="promise-vocabulary">Promise vocabulary</h2>
        </header>
        <article>
            <section>
                <p>
                    This section refers specifically to the vocabulary used in this document to make finding specific examples easier, though the code samples themselves should be self explanatory.
                </p>
                <ul>
                    <li>
                        <strong>Promise</strong> - An object which represents the eventual result of an asynchronous
                        operation. <code>new Promise()</code>, <code>Promise.resolve()</code>,
                        <code>Promise.reject()</code> all return a promise object;
                    </li>
                    <li>
                        <strong>Executor</strong> - A function passed to Promise constructor, ie. <code>new Promise(&lt;executor&gt;)</code>
                        and takes two callback arguments, one for resolving the promise and one for rejecting it: <code>function
                        executor(resolve, reject)</code>;
                    </li>
                    <li>
                        <strong>Then()</strong> - A method of a promise object which takes two optional callback
                        arguments, one for handling the case when the promise is resolved (fulfilled) and another for
                        when it is rejected, ie: <code>.then(onResolved, onRejected)</code>. It returns a new promise
                        which is pending until Then is handled.
                    </li>
                    <li>
                        <strong>onResolved</strong> - One of the two possible promise handlers, defined in Then(), is
                        called when the promise to which it is attached is resolved. This can happen by: explicitly
                        resolving promise, returning from <i>onResolved</i> or <i>onRejected</i> any value other than a
                        rejected promise, not returning anything from either of those handlers.
                    </li>
                    <li>
                        <strong>onRejected</strong> - One of the two possible promise handlers, defined in Then(), is
                        called when the promise to which it is attached is rejected. This can happen by: explicitly
                        rejecting promise, returning from <i>onResolved</i> or <i>onRejected</i> a rejected promise,
                        throwing an error inside a promise handler.
                    </li>
                </ul>
            </section>
        </article>
    </section>

    <section class="promise-group">
        <header>
            <h2>Basic promise behaviors</h2>
        </header>

        <article class="promise-article">
            <header>
                <h3>Promise executor is called immediately upon promise creation</h3>
            </header>
            <section>
                <pre class="code"><code>
                    <script>
                        var promise = new Promise(function () {
                            log("Promise was run.");
                        });

                        log("End of script.");
                    </script>
                </code></pre>
                <ol class="results"></ol>
            </section>
        </article>
        <article class="promise-article">
            <header>
                <h3>Then() resolution is asynchronous</h3>
            </header>
            <section>
                <pre class="code"><code>
                    <script>
                        Promise.resolve().then(function () {
                            log("On resolved");

                        }, function () {
                            log("On rejected - not run because promise is resolved")
                        });

                        Promise.reject().then(function () {
                            log("On resolved - not run because promise is rejected");

                        }, function () {
                            log("On rejected")
                        });

                        log("End of script.");
                    </script>
                </code></pre>
                <ol class="results"></ol>
            </section>
        </article>

        <article class="promise-article">
            <header>
                <h3>Then() by default resolve the returned promise, with the single exception of returning a rejected
                    promise</h3>
            </header>
            <section>
                <pre class="code"><code>
                    <script>
                        Promise.resolve().then(function () {
                            // Nothing is returned
                        }).then(function () {
                            log("Resolved from nothing returned");
                            return true;

                        }).then(function () {
                            log("Resolved from return true");
                            return false;

                        }).then(function () {
                            log("Resolved from return false");
                            return null;

                        }).then(function () {
                            log("Resolved from return null");
                            return Promise.reject();

                        }).then(function () {
                            log("Not called because a rejected promise was returned");
                        });
                    </script>
                </code></pre>
                <ol class="results"></ol>
            </section>
        </article>
        <article class="promise-article">
            <header>
                <h3>Rejected promise skips all onResolved handlers</h3>
            </header>
            <section>
                <pre class="code"><code>
                    <script>
                        Promise.reject().then(function () {
                            log("Never called #1");

                        }).then(function () {
                            log("Never called #2");

                        }).then(function () {
                            log("Never called #3");

                        }).then(function () {
                            log("Never called #4");

                        }).catch(function () {
                            log("First available onRejected handler")
                        });
                    </script>
                </code></pre>
                <ol class="results"></ol>
            </section>
        </article>
        <article class="promise-article">
            <header>
                <h3>Throwing an error rejects a promise</h3>
            </header>
            <section>
                <pre class="code"><code>
                    <script>
                        Promise.resolve().then(function () {
                            throw new Error();

                        }).then(function () {
                            log("Never called because of the thrown error");

                        }).catch(function () {
                            log("Throwing an error rejects the promise");
                        });
                    </script>
                </code></pre>
                <ol class="results"></ol>
            </section>
        </article>
        <article class="promise-article">
            <header>
                <h3>Returnin nothing inside catch stops the rejection</h3>
            </header>
            <section>
                <pre class="code"><code>
                    <script>
                        Promise.resolve().then(function () {
                            throw new Error();

                        }).then(function () {
                            log("Never called because of the thrown error");

                        }).catch(function () {
                            log("Throwing an error rejects the promise");

                        }).then(function(){
                            log("Called because nothing was returned from catch");

                        }).catch(function(){
                            log("Never called");
                        })
                    </script>
                </code></pre>
                <ol class="results"></ol>
            </section>
        </article>

        <article class="promise-article">
            <header>
                <h3>Nested promises are handled first</h3>
            </header>
            <section>
                <pre class="code"><code>
                    <script>
                        Promise.resolve().then(function () {

                            return Promise.resolve().then(function () {
                                log("This promise tree has to finish first.");

                            }).then(function () {
                                log("Yet another step inside.");

                            }).then(function () {
                                log("Resolved the nested promise tree.");
                            });

                        }).then(function () {
                            log("This is only handled once the inner promise is finished.");
                        });
                    </script>
                </code></pre>
                <ol class="results"></ol>
            </section>
        </article>

        <article class="promise-article">
            <header>
                <h3>Passing non-function to then ignores that 'then'</h3>
            </header>
            <section>
                <pre class="code"><code>
                    <script>
                        Promise.resolve("This string is logged")
                            .then("This will not be logged")
                            .then(log);
                    </script>
                </code></pre>
                <ol class="results"></ol>
            </section>
        </article>
    </section>

    <section class="promise-group">
        <header>
            <h2>Complex promise behaviors</h2>
        </header>

        <article class="promise-article">
            <header>
                <h3>Calling then() twice on the same promise is valid and creates two separate promise branches</h3>
            </header>
            <section>
                <pre class="code"><code>
                    <script>
                        var promise = Promise.resolve();

                        promise.then(function(){
                            log('Branch #1 - do a reject');
                            return Promise.reject();

                        }).then(function(){
                            log("Resolve handler not called because previous promise was rejected")
                        });

                        promise.then(function(){
                            log('Branch #2 - do a resolve');
                            return Promise.resolve();

                        }).catch(function(){
                            log('Caught reject - not called because rejection happened in the other branch')
                        });

                        log("End of script.");
                    </script>
                </code></pre>
                <ol class="results"></ol>
            </section>
        </article>

        <article class="promise-article">
            <header>
                <h3>Errors thrown inside the executor automatically reject the promise</h3>
            </header>
            <section>
                <pre class="code"><code>
                    <script>
                        var promise = new Promise(function(){
                            log("Throwing an error");
                            throw new Error("Error");
                        });

                        promise.catch(function(){
                            log("Error was caught")
                        });
                    </script>
                </code></pre>
                <ol class="results"></ol>
            </section>
        </article>

        <article class="promise-article">
            <header>
                <h3>Returning a resolved promise in executor does not resolve the promise</h3>
            </header>
            <section>
                <pre class="code"><code>
                    <script>
                        var promise = new Promise(function(){
                            log("Returning a resolved promise");
                            return Promise.resolve();
                        });

                        promise.then(function(){
                            log("This is never called")
                        });
                    </script>
                </code></pre>
                <ol class="results"></ol>
            </section>
        </article>

        <article class="promise-article">
            <header>
                <h3>Resolving the promise multiple times ignores the subsequent calls</h3>
            </header>
            <section>
                <pre class="code"><code>
                    <script>
                        var promise = new Promise(function(resolve){
                            log("First resolve call");
                            resolve();
                            log("Second resolve call");
                            resolve();
                            log("Third resolve call");
                            resolve();
                        });

                        promise.then(function(){
                            log("Resolved the promise")
                        });
                    </script>
                </code></pre>
                <ol class="results"></ol>
            </section>
        </article>
    </section>
</article>
</body>
</html>